version: '3.7'

services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keicommu_development
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  api:
    tty: true
    depends_on:
      - db
    build:
      context: ../KeiCommu_Api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../KeiCommu_Api:/app
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && rails s -b 0.0.0.0"
  front:
    build:
      context: ../KeiCommu_Front/
      dockerfile: Dockerfile
    volumes:
      - ../KeiCommu_Front/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - '8000:3000'
volumes:
  mysql-db:
    driver: local
